// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoR2Logbook.Models;

namespace RoR2Logbook.Migrations
{
    [DbContext(typeof(RoR2LogbookContext))]
    [Migration("20190425060719_Comments")]
    partial class Comments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoR2Logbook.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Icon");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("RoR2Logbook.Models.ItemComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commenter");

                    b.Property<string>("Date");

                    b.Property<string>("ItemID");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("ItemComment");
                });

            modelBuilder.Entity("RoR2Logbook.Models.Survivor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BaseDamage");

                    b.Property<float>("BaseMaxHealth");

                    b.Property<float>("DamageIncrease");

                    b.Property<string>("Icon");

                    b.Property<float>("MaxHealthIncrease");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<float>("Speed");

                    b.HasKey("ID");

                    b.ToTable("Survivor");
                });

            modelBuilder.Entity("RoR2Logbook.Models.SurvivorComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commenter");

                    b.Property<string>("Date");

                    b.Property<string>("SurvivorID");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("SurvivorComment");
                });
#pragma warning restore 612, 618
        }
    }
}
